language: node_js

node_js:
    - '8'

jobs:
    include:
        - stage: test
          script:
              - npm run lint
              - npm run test
        - stage: deploy
          if: branch = release
          deploy:
              - provider: script
                skip_cleanup: true
                script:
                    - npx semantic-release
