language: node_js

node_js:
    - '8'

jobs:
    include:
        - stage: test
          script:
              - npm run lint
              - npm run test
        - stage: deploy
          if: branch = release
          script:
              - npx semantic-release
