language: node_js

node_js:
    - '10'

cache:
    npm: false

addons:
    hosts:
        - localhost.paypal.com

before_install:
    - npm i -g npm@6

before_script:
    - npm run dev:standalone &
    - sleep 30

script:
    - ./scripts/snapshot-tests/run-tests.sh
    - npm run lint
    - npm run test

deploy:
    provider: script
    skip_cleanup: true
    script:
        - npx semantic-release
    on:
        branch: release
