name: Node CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install, build, and test
              run: |
                  echo "localhost.paypal.com  127.0.0.1" >> /etc/hosts
                  npm install
                  npm run dev:standalone &
                  sleep 20
                  npm run test:func
              env:
                  CI: true
