name: Node CI

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install, build, and test
              run: |
                  echo "127.0.0.1 localhost.paypal.com" | sudo tee -a /etc/hosts
                  npm install
                  npm run dev:standalone &
                  sleep 20
                  ./scripts/snapshot-tests/run-tests.sh
              env:
                  CI: true
